service: aws-java-maven-fibonacci

provider:
  name: aws
  runtime: java8
  timeout: 30

package:
  artifact: target/fibonacci-dev.jar

functions:
  fibonacci:
    handler: com.serverless.Handler
    events:
      - http:
          path: /
          method: get
