
service: aws-rust
provider:
  name: aws
  runtime: rust

package:
  individually: true

plugins:
  - serverless-rust

functions:
  fibonacci:
    handler: fibonacci
    events:
      - http:
          path: /
          method: get
