
service: aws-rust-fibonacci
provider:
  name: aws
  runtime: rust
  timeout: 30

package:
  individually: true

plugins:
  - serverless-rust

functions:
  fibonacci:
    handler: fibonacci
    events:
      - http:
          path: /
          method: get
